import Head from 'next/head'
import styles from '@/styles/Common.module.scss'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import FaqItem from '@/components/FaqItem'

const FAQ_ITEMS = [
  {
    title: 'Is UpLink Health suitable for everyone?',
    description: [
      'Our online service requires our doctors and nurse practitioners to take extra care than they would during an in-person visit, making it unsuitable for everyone. Therefore, we may not be able to provide our services to everyone who wishes to use our service.',
      "We follow strict guidelines to ensure that we prescribe medication only when it's safe and appropriate for you. If we feel that our service isn't in your best interest based on your health history or symptoms, we'll suggest that you see a healthcare provider in person, and we'll refund your consultation fee."
    ],
    isShow: true,
  },
  {
    title: 'How quickly will my treatment request be reviewed?',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'How easy is it to postpone or cancel medicine deliveries?',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
];

export default function FAQ() {
  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name='description' content='Generated by Uplink Health' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.hero1}`}>
          <div className='flex px-4 py-8 lg:px-24 lg:py-16 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-col flex-1 justify-center items-center'>
              <h1 className='text-xl lg:text-3xl font-weight-bold leading-tight text-center'>Frequently Asked Questions</h1>
            </div>
          </div>
        </div>
        <div className={`w-full flex flex-1 ${styles.bgWhite}`}>
          <div className='flex flex-col px-4 py-4 lg:px-24 lg:py-16 container mx-auto'>
            <p className='text-sm lg:text-lg font-weight-500 mt-2 mb-4 text-gray-600'>
              At UpLink Health, we understand the value of your time and money. Our aim is to provide excellent healthcare without requiring an in-person visit. This means you don't have to book an appointment, travel to and from the doctor's office or wait in a waiting room. Plus, we offer a mail order pharmacy for added convenience.
            </p>
            <p className='text-sm lg:text-lg font-weight-500 mt-2 mb-4 text-gray-600'>
              Our consultation fee for most services is only $25, which is often less than the cost of most insurance copays. Some services, such as our depression and anxiety service, come at a flat fee per month, covering consultations and any prescribed medicines we deliver.
            </p>
            <div className='my-3'>
              {FAQ_ITEMS.map((item, index) => (
                <FaqItem title={item.title} description={item.description} key={'faqitem_' + index} />
              ))}
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
