import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Navbar from '@/components/Navbar'
import Button, { ButtonType } from '@/components/Button'
import Divider from '@/components/Divider'
import Card from '@/components/Card'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name="description" content="Generated by Uplink Health" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.hero1}`}>
          <div className='flex px-4 py-4 lg:px-24 lg:py-16 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-col flex-1 justify-center'>
              <Divider className='my-4 lg:my-8' />
              <h1 className='text-2xl lg:text-6xl font-weight-bold leading-tight'>Prescription medications <br />online for E.D. delivered<br />straight to your door</h1>
              <p className='text-xs lg:text-2xl font-weight-bold mt-10'>Generic Cialis(Tadalafil) & Generic Viagra(Sildenafil)</p>
              <Button title="Let's begin!" containerClassName="mt-10" type={ButtonType.redOutline} />
            </div>
            <div className='mx-auto flex items-center mt-4 lg-mt-0 lg:ml-6 lg:mr-12'>
              <Image
                src="/imgs/hero-img-1.png"
                alt="prescription"
                width={500}
                height={400}
              />
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1'>
              <Image
                src="/imgs/hero-img-2.png"
                alt="prescription"
                width={600}
                height={400}
              />
            </div>
            <div className='flex flex-1 flex-col items-center justify-center mt-6 lg:mt-0'>
              <div>
                <h1 className='text-3xl font-weight-bold leading-tight'>Existing ED patient?</h1>
                <p className='text-sm lg:text-2xl font-weight-bold mt-2'>Script renewal consultations are FREE.</p>
                <Divider className='my-4 lg:my-8' />

                <div className='flex items-center'>
                  <Image
                    src="/imgs/check-circle-icon.png"
                    alt="check-circle-icon"
                    width={16}
                    height={16}
                  />
                  <p className='text-md lg:text-lg font-weight-bold mt-2 mb-2 ml-3'>Prices starting at $2 per pill</p>
                </div>
                <div className='flex items-center'>
                  <Image
                    src="/imgs/check-circle-icon.png"
                    alt="check-circle-icon"
                    width={16}
                    height={16}
                  />
                  <p className='text-md lg:text-lg font-weight-bold mt-2 mb-2 ml-3'>Exactly the same as brand name Viagra and Cialis</p>
                </div>
                <div className='flex items-center'>
                  <Image
                    src="/imgs/check-circle-icon.png"
                    alt="check-circle-icon"
                    width={16}
                    height={16}
                  />
                  <p className='text-md lg:text-lg font-weight-bold mt-2 mb-2 ml-3'>Packages are shipped discreetly for free</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.hero3}`}>
          <div className='flex flex-col px-4 py-4 lg:px-24 lg:py-24 container mx-auto'>
            <div className='flex w-full items-center flex-col'>
              <h1 className='text-3xl font-weight-600 text-center'>An Overview of the process</h1>
              <Divider className='my-4 lg:my-8' />
            </div>
            <div className='flex items-stretch flex-col lg:flex-row'>
              <Card
                header="Free Private Online Evaluation"
                description="Let us know how you are feeling and what medications you are taking."
                icon="/imgs/checklist.png"
                orderNumber='01'
              />
              <Card
                header="You will be contacted within 24 hours by a doctor or nurse pratitioner."
                description="You will be notified if a video chat is required, or if a phone consultation is only necessary."
                icon="/imgs/video-call.png"
                orderNumber='02'
              />
              <Card
                header="Your prescription will be delivered quickly for FREE"
                description="The response time is normally 2-3 days"
                icon="/imgs/product.png"
                orderNumber='03'
              />
              <Card
                header="The service is delivered monthly for 12months and can be canceled at any time."
                description="Just give us a call or send a message!"
                icon="/imgs/call.png"
                orderNumber='04'
              />
            </div>
          </div>
        </div>

        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 flex-col items-center justify-center'>
              <div>
                <h1 className='text-3xl font-weight-bold leading-tight'>Give us a call.</h1>
                <p className='text-2xl font-weight-bold mt-2'>Whenever you need us, we're here to help</p>
                <Divider className='my-4 lg:my-8' />
                <div className='flex'>
                  <Image
                    src="/imgs/clock-circle-icon.png"
                    alt="clock-circle-icon"
                    width={20}
                    height={20}
                    className={'h-fit mt-4'}
                  />
                  <div className='ml-4'>
                    <p className='text-lg font-weight-bold mt-2 mb-2'>Monday-Friday, 9am-5pm Eastern Standard Time</p>
                    <p className='text-lg font-weight-bold mt-2 mb-2'>Saturday-Sunday 9am-3pm Eastern Standard Time</p>
                  </div>
                </div>

                <div className='p-10 rounded-3xl border-2 border-green-600 mt-10'>
                  <p className='text-lg font-weight-600 text-center'>New York-based Uplink-Health is a national<br /> provider of telehealth services</p>
                </div>
              </div>
            </div>
            <div className='flex flex-1 justify-end mt-4 lg:mt-0'>
              <Image
                src="/imgs/business-women-call.png"
                alt="business-women-call"
                width={600}
                height={400}
              />
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className={`flex flex-1 items-center rounded-t-2xl lg:rounded-2xl p-10 lg:mr-5 ${styles.infoCard} flex-col lg:flex-row`}>
              <Image
                src="/imgs/young-male-psysician-with.png"
                alt="young-male-psysician-with"
                width={278}
                height={377}
              />
              <div className='p-5'>
                <p className='text-xl lg:text-2xl font-weight-bold mt-2'>For our healthcare team to prescribe ED medications, we need your blood pressure</p>
                <Divider className='my-4 lg:my-8' />
                <p className='text-sm lg:text-lg font-weight-600 text-gray-600'>Contact your doctor or find a machine near you to check your blood pressure if you don't already know it.</p>
              </div>
            </div>
            <div className={`flex flex-1 items-center rounded-b-2xl lg:rounded-2xl p-10 lg:ml-5 ${styles.infoCard} flex-col lg:flex-row`}>
              <Image
                src="/imgs/close-up-man-sitting.png"
                alt="close-up-man-sitting"
                width={278}
                height={377}
              />
              <div className='p-5'>
                <p className='text-xl lg:text-2xl font-weight-bold mt-2'>By the age of 40, 40% of men will have suffered from ED</p>
                <Divider className='my-4 lg:my-8' />
                <p className='text-sm lg:text-lg font-weight-600 text-gray-600'>Erectile Dysfunction</p>
                <Button title="Learn More" containerClassName='mt-5' type={ButtonType.redOutline} />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
