import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Product.module.scss'
import Navbar from '@/components/Navbar'
import Button, { ButtonType } from '@/components/Button'
import Divider from '@/components/Divider'
import Card from '@/components/Card'
import Footer from '@/components/Footer'
import BenefitItem from '@/components/BenefitItem'

const BENEFIT_ITEMS = [
  {
    title: 'What is it and how does it work?',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: true,
  },
  {
    title: 'What is Sildenafil?',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'How does Sildenafil work? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'What are the benefits of Sildenafil? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'What are the potential side effects of Sildenafil? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'Is Sildenafil safe for everyone? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
];

export default function Product() {
  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name='description' content='Generated by Uplink Health' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.hero1}`}>
          <div className='flex px-24 py-16 container mx-auto'>
            <div className='flex flex-col flex-1 justify-center items-center'>
              <h1 className='text-3xl font-weight-bold leading-tight'>Sildenafil</h1>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 my-4 lg:my-0'>
              <Image
                src='/imgs/running.png'
                alt='prescription'
                width={600}
                height={400}
                className={'rounded-2xl'}
                priority
              />
            </div>
            <div className='flex flex-1 flex-col items-center justify-center lg:ml-3'>
              <div>
                <h1 className='text-xl lg:text-3xl font-weight-bold leading-tight'>Sildenafil</h1>
                <Divider className='my-4 lg:my-8' />
                <p className='text-md lg:text-lg font-weight-bold mt-2 mb-2 text-gray-600'>There are four different doses of sildenafil pills available, but the most affordable option is the 20mg pill. Our internet-based pharmacy offers these pills for $2 each, which includes complimentary delivery.</p>
                <Button title='Get Started' containerClassName='mt-4' type={ButtonType.redOutline} />
              </div>
            </div>
          </div>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 flex-col items-center lg:ml-3'>
              {BENEFIT_ITEMS.map((item, key) => (
                <BenefitItem
                  title={item.title}
                  description={item.description}
                  isShow={item.isShow}
                  key={key}
                />
              ))}
            </div>
            <div className='flex flex-1 justify-end my-4 lg:my-0'>
              <Image
                src='/imgs/couple.png'
                alt='prescription'
                width={600}
                height={400}
                className={'rounded-2xl h-fit'}
                priority
              />
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.hero3}`}>
          <div className='flex flex-col px-4 py-4 lg:px-24 lg:py-24 container mx-auto'>
            <div className='flex w-full items-center flex-col'>
              <h1 className='text-xl lg:text-3xl font-weight-600'>Sildenafil is available in various strengths to suit different needs.</h1>
              <Divider className='my-4 lg:my-8' />
            </div>
            <div className='flex flex-col items-stretch'>
              <p className='text-sm lg:text-lg text-gray-600 font-weight-600 mb-5'>Generic 20mg pills are a low-cost option, and if one of our UpLink Health healthcare professionals recommends them for you, they will advise you to take either 1, 3, or 5 pills at a time depending on your individual situation. One 20mg pill equals a 20mg dose, three pills equals a 60mg dose, and five pills equals a 100mg dose, which are equivalent to the more expensive sildenafil 25mg, sildenafil 50mg, and sildenafil 100mg doses. For individuals who have never taken these medications before, a typical starting dose is 60mg or three 20mg pills. Pfizer also makes a more expensive branded version of the 20mg pill called Revatio, while generic versions of the 20mg pill are a cost-effective way to obtain ED medications.</p>
              <p className='text-sm lg:text-lg text-gray-600 font-weight-600 mb-3'>In addition to generic 20mg pills, sildenafil also comes in more expensive 25mg, 50mg, and 100mg doses. Pfizer manufactures both branded and generic versions of the 25mg, 50mg, and 100mg pills, which are sold under the name Viagra.</p>
            </div>
          </div>
        </div>

        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 flex-col items-center justify-center lg:ml-3'>
              <div>
                <h1 className='text-xl lg:text-3xl font-weight-bold leading-tight'>Sildenafil 20mg and <br />its approval by the FDA </h1>
                <Divider className='my-4 lg:my-8' />
                <p className='text-sm lg:text-lg font-weight-bold mt-2 mb-2 text-gray-600'>The FDA has approved sildenafil in 25mg, 50mg, and 100mg doses for the treatment of erectile dysfunction. However, the 20mg dose is not FDA-approved for treating ED. Instead, it has been approved for the treatment of pulmonary hypertension. Using the 20mg dose for erectile dysfunction would mean taking it off-label.</p>
              </div>
            </div>
            <div className='flex flex-1 justify-center my-4 lg:my-0'>
              <Image
                src='/imgs/certification.png'
                alt='certification'
                width={200}
                height={200}
                className={'rounded-2xl h-fit'}
                priority
              />
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className={`flex flex-1 flex-col justify-center items-center rounded-2xl py-10 lg:p-10 lg:mr-5 ${styles.infoCard}`}>
              <h1 className='text-xl lg:text-3xl font-weight-bold leading-tight'>How it works</h1>
              <Divider className='my-4 lg:my-8' />
              <div className='flex flex-1 px-4 lg:px-12 mb-6 flex-col lg:flex-row'>
                <Card
                  header="Assessment for treatment"
                  description="Your responses are confidential and help us understand you individual situation."
                  icon="/imgs/clipboard.png"
                  iconContainerStyle={"p-4"}
                  containerStyle={"px-4 lg:px-10 items-center"}
                  headerStyle={'text-center'}
                  textStyle={'text-center'}
                />
                <Card
                  header="Personalized Consultation"
                  description="A licensed healthcare provider will contact you within 24 hours to discuss treatment options that are best suited for your needs"
                  icon="/imgs/doctor.png"
                  iconContainerStyle={"p-4"}
                  containerStyle={"px-4 lg:px-10 items-center"}
                  headerStyle={'text-center'}
                  textStyle={'text-center'}
                />
                <Card
                  header="Fast and convenient delivery"
                  description="Enjoy free shipping that delivers to your door within 2-3 business days. Refills are automatically sent monthly for up to 11 times, and you can cancel anytime."
                  icon="/imgs/shipped.png"
                  iconContainerStyle={"p-4"}
                  containerStyle={"px-4 lg:px-10 items-center"}
                  headerStyle={'text-center'}
                  textStyle={'text-center'}
                />
              </div>
              <Button title="Get Started" type={ButtonType.redOutline} />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
