import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Product.module.scss'
import Navbar from '@/components/Navbar'
import Button, { ButtonType } from '@/components/Button'
import Divider from '@/components/Divider'
import Card from '@/components/Card'
import Footer from '@/components/Footer'
import BenefitItem from '@/components/BenefitItem'

const BENEFIT_ITEMS = [
  {
    title: 'What is Tadalafil?',
    description: "Tadalafil is the active ingredient in the branded drug Cialis and is approved by the FDA to treat erectile dysfunction. It's available in 5mg, 10mg, and 20mg strengths at UpLink Health. However, we do not prescribe the 2.5mg dose.",
    isShow: true,
  },
  {
    title: 'Why is it called generic Cialis?',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'Can I have generic Cialis mailed to me? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'What are the differences between the doses? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'Do I need a prescription for Tadalafil? ',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
  {
    title: 'What is it and how does it work?',
    description: 'Sildenafil is the active ingredient in Viagra and is one of the most commonly prescribed medications for erectile dysfunction (ED). This medication works by relaxing blood vessels and increasing blood flow to the penis, allowing men to achieve and maintain an erection.',
    isShow: false,
  },
];

export default function Product() {
  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name='description' content='Generated by Uplink Health' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.hero1}`}>
          <div className='flex px-24 py-16 container mx-auto'>
            <div className='flex flex-col flex-1 justify-center items-center'>
              <h1 className='text-3xl font-weight-bold leading-tight'>Tadalafil</h1>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 my-4 lg:my-0'>
              <Image
                src='/imgs/running-1.png'
                alt='prescription'
                width={600}
                height={400}
                className={'rounded-2xl'}
                priority
              />
            </div>
            <div className='flex flex-1 flex-col items-center justify-center lg:ml-3'>
              <div>
                <h1 className='text-xl lg:text-3xl font-weight-bold leading-tight'>Tadalafil (Generic Cialis)</h1>
                <Divider className='my-4 lg:my-8' />
                <p className='text-md lg:text-lg font-weight-500 mt-2 mb-4 text-gray-600'>If you're experiencing erectile dysfunction, Tadalafil can be prescribed by one of our licensed healthcare professionals and conveniently delivered to you via mail. With UpLink Health, you can receive a prescription for 10 Generic Cialis pills at a time, with 11 refills. Before starting a visit, please ensure you know your blood pressure.</p>
                <p className='text-md lg:text-lg font-weight-bold mt-2 mb-2 text-gray-600'>It's estimated that 52% of men experience some form of erectile dysfunction throughout their lives.</p>
                <Button title='Get Started' containerClassName='mt-4' type={ButtonType.redOutline} />
              </div>
            </div>
          </div>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 flex-col items-center lg:ml-3'>
              {BENEFIT_ITEMS.map((item, key) => (
                <BenefitItem
                  title={item.title}
                  description={item.description}
                  isShow={item.isShow}
                  key={key}
                />
              ))}
            </div>
            <div className='flex flex-1 justify-end my-4 lg:my-0'>
              <Image
                src='/imgs/couple-1.png'
                alt='prescription'
                width={600}
                height={400}
                className={'rounded-2xl h-fit'}
                priority
              />
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className={`flex flex-1 flex-col justify-center items-center rounded-2xl py-10 lg:p-10 lg:mr-5 ${styles.infoCard}`}>
              <h1 className='text-2xl lg:text-3xl font-weight-bold leading-tight'>How it works</h1>
              <Divider className='my-4 lg:my-8' />
              <div className='flex flex-1 px-4 lg:px-12 mb-6 flex-col lg:flex-row'>
                <Card
                  header="Assessment for treatment"
                  description="Your responses are confidential and help us understand you individual situation."
                  icon="/imgs/clipboard.png"
                  iconContainerStyle={"p-4"}
                  containerStyle={"px-4 lg:px-10 items-center"}
                  headerStyle={'text-center'}
                  textStyle={'text-center'}
                />
                <Card
                  header="Personalized Consultation"
                  description="A licensed healthcare provider will contact you within 24 hours to discuss treatment options that are best suited for your needs"
                  icon="/imgs/doctor.png"
                  iconContainerStyle={"p-4"}
                  containerStyle={"px-4 lg:px-10 items-center"}
                  headerStyle={'text-center'}
                  textStyle={'text-center'}
                />
                <Card
                  header="Fast and convenient delivery"
                  description="Enjoy free shipping that delivers to your door within 2-3 business days. Refills are automatically sent monthly for up to 11 times, and you can cancel anytime."
                  icon="/imgs/shipped.png"
                  iconContainerStyle={"p-4"}
                  containerStyle={"px-4 lg:px-10 items-center"}
                  headerStyle={'text-center'}
                  textStyle={'text-center'}
                />
              </div>
              <Button title="Get Started" type={ButtonType.redOutline} />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
