import Head from 'next/head'
import styles from '@/styles/Common.module.scss'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Tabs from '@/components/Tabs'
import { useEffect, useState } from 'react'
import Membership from '@/components/profiles/Membership'
import Orders from '@/components/profiles/Orders'
import Profile from '@/components/profiles/Profile'
import Case from '@/components/profiles/Case'
import LocalAPIClient from '@/utils/localApi';
import { useRouter } from 'next/router'

const TAB_ITEMS = [
  {
    name: 'Membership',
    url: '#',
    id: 'membership',
  },
  {
    name: 'Orders',
    url: '#',
    id: 'orders',
  },
  {
    name: 'Profile',
    url: '#',
    id: 'profile',
  },
  {
    name: 'Case',
    url: '#',
    id: 'case',
  },
  {
    name: 'ID Verification',
    url: '#',
    id: 'id_verification',
  },
];

const ProfilePage = () => {
  const router = useRouter();
  const [activeTabIndex, setActiveTabIndex] = useState(0);
  const handleChangeActiveTab = (tabIndex: number) => {
    setActiveTabIndex(tabIndex);
  };
  const [user, setUser]: any = useState(null);

  const getData = async () => {
    const _user = await LocalAPIClient.get('/api/user/profile');
    setUser(_user);

    if (!_user) {
      router.push('/auth/login');
    }
  };
  
  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name='description' content='Generated by Uplink Health' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex flex-col px-4 py-4 lg:px-24 lg:py-24 container mx-auto'>
            <Tabs tabs={TAB_ITEMS} onChangeActiveTab={(index: number) => handleChangeActiveTab(index)} />
            <div className='flex flex-col justify-center items-center py-12'>
              {activeTabIndex === 0 && (
                <Membership />
              )}
              {activeTabIndex === 1 && (
                <Orders />
              )}
              {activeTabIndex === 2 && (
                <Profile />
              )}
              {activeTabIndex === 3 && (
                <Case />
              )}
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}

export const getServerSideProps = async(context: any) => {

  return {
    props: {},
  }
}

export default ProfilePage;