import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Common.module.scss'
import Navbar from '@/components/Navbar'
import Button, { ButtonType } from '@/components/Button'
import Footer from '@/components/Footer'
import Link from 'next/link'

export default function Recommendation() {
  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name='description' content='Generated by Uplink Health' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.hero1}`}>
          <div className='flex px-4 py-4 lg:px-24 lg:py-16 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-col flex-1 justify-center items-center'>
              <h1 className='text-2xl lg:text-3xl font-weight-bold leading-tight text-center'>RECOMMENDED PILL FOR ED TREATMENT</h1>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex flex-col justify-between px-4 py-4 pt-12 lg:px-24 lg:py-16 container mx-auto'>
            <p className='text-md lg:text-lg font-weight-500 mt-2 mb-4 text-gray-600'>A starting dosage of 60mg is the most common for men who are new to ED medication.</p>
            <p className='text-md lg:text-lg font-weight-500 mt-2 mb-8 text-gray-600'>Based on the information you provided, a physician will determine if this dosage is right for you, or recommend a more appropriate dosage. </p>

            <div className='flex flex-1 p-4 lg:p-8 bg-white shadow-xl rounded-xl border border-gray flex-col lg:flex-row'>
              <div className='flex flex-1 flex-col'>
                <Button title='Recommended for you' buttonClassName='bg-[#515151] rounded-lg mr-2 py-4 text-white' />
                <p className='text-2xl lg:text-3xl font-weight-bold my-12'>Generic<br />Viagra®</p>
                <Image
                  src='/imgs/recommendation-sildenafil-bg.png'
                  alt='prescription'
                  width={500}
                  height={400}
                  className={'rounded-2xl h-fit mt-4'}
                  priority
                />
              </div>
              <div className='flex flex-1 flex-col mt-4 lg:mt-0 lg:ml-4'>
                <Image
                  src='/imgs/sildenafil-effect.png'
                  alt='prescription'
                  width={600}
                  height={400}
                  className={'rounded-2xl h-fit'}
                  priority
                />
                <div className='flex items-center rounded-lg bg-[#d1e7f0] p-4 mt-4'>
                  <div className='flex'>
                    <p className='text-xs lg:text-lg font-weight-500'>Ready:</p>
                    <p className='text-xs lg:text-lg font-weight-bold ml-2'>20m-30m</p>
                  </div>
                  <div className='flex flex-1 items-center justify-center'>
                    <p className='text-xs lg:text-lg font-weight-500'>Peak:</p>
                    <p className='text-xs lg:text-lg font-weight-bold ml-2'>1h</p>
                  </div>
                  <div className='flex'>
                    <p className='text-xs lg:text-lg font-weight-500'>In System:</p>
                    <p className='text-xs lg:text-lg font-weight-bold ml-2'>12h</p>
                  </div>
                </div>
                <div className='flex flex-col my-4 p-4'>
                  <div className='green-dot-item text-md lg:text-lg my-2 lg:my-4 font-weight-500'>Sildenafil is the same active ingredient as Viagra®</div>
                  <div className='green-dot-item text-md lg:text-lg my-2 lg:my-4 font-weight-500'>The most popular ED treatment for men</div>
                </div>
                <Button title='Continue' type={ButtonType.redOutline} containerClassName={"flex items-center justify-center lg:mt-12"} />
              </div>
            </div>
            <p className='flex items-center justify-center text-md lg:text-lg font-weight-500 mb-4 text-gray-600 mt-12 flex-col lg:flex-row'>
              <span>Prefer a different medication?</span>
              <Link href={'#'} className="text-[#45a46c] ml-2">See all options</Link>
            </p>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
