import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/ServiceDelivery.module.scss'
import Navbar from '@/components/Navbar'
import Button, { ButtonType } from '@/components/Button'
import Divider from '@/components/Divider'
import Footer from '@/components/Footer'

const SHIPPING_ITEMS = [
  {
    text: 'Starting at $2/pill',
  },
  {
    text: 'Same ingredient as brand names Viagra and Cialis',
  },
  {
    text: 'Discreet package & FREE shipping 2-3 business days',
  },
];

export default function ServiceDelivery() {
  return (
    <>
      <Head>
        <title>Uplink Health</title>
        <meta name='description' content='Generated by Uplink Health' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={`w-full ${styles.hero1}`}>
          <div className='relative flex px-4 py-4 pb-16 lg:px-24 lg:py-16 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-col items-center'>
              <Image
                src='/imgs/delivery-bg-1.png'
                alt='medicine'
                width={500}
                height={400}
                className={'rounded-2xl'}
                priority
              />
            </div>
            <div className='flex flex-col flex-1 justify-center lg:ml-10'>
              <h1 className='text-2xl lg:text-4xl font-weight-bold my-4 leading-normal'>
                Discover unprecedented savings of<br />
                up to 70% off your initial purchase with us!
              </h1>
              <p className='text-md lg:text-2xl font-weight-700 lg:font-weight-500 mt-4 mb-2 leading-normal'>
                We offer prescribed erectile dysfunction medication delivered straight to your doorstep for optimal convenience.
              </p>
              <p className='text-md lg:text-2xl font-weight-700 lg:font-weight-500 mt-4 leading-normal mb-8'>
                Our selection includes the highly effective and affordable options of Generic Viagra (Sildenafil) and Generic Cialis (Tadalafil).
              </p>
              <Button title="Let's begin!" type={ButtonType.redOutline} />
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-8 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 justify-end'>
              <Image
                src='/imgs/delivery-bg-2.png'
                alt='prescription'
                width={600}
                height={400}
                className={'rounded-2xl'}
                priority
              />
            </div>
            <div className='flex flex-1 flex-col justify-center lg:ml-3'>
              <div className='lg:pl-24'>
                {SHIPPING_ITEMS.map((item, index) => (
                  <div className='flex flex-1 my-4 lg:my-12' key={'shipping_' + index}>
                    <Image
                      src='/imgs/checked-square.png'
                      alt='check'
                      width={36}
                      height={36}
                      className={'h-fit w-4 lg:w-auto mt-2 lg:mt-0'}
                      priority
                    />
                    <p className='text-md lg:text-2xl font-weight-500 ml-4 lg:ml-10'>{item.text}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.hero2}`}>
          <div className='flex flex-col px-4 py-4 lg:px-24 lg:py-24 container mx-auto'>
            <div className='flex flex-1 flex-col items-center justify-center lg:ml-3'>
              <h1 className='text-2xl lg:text-3xl font-weight-bold leading-tight'>
                How it works
              </h1>
              <Divider className='my-4 lg:my-8' />
              <div className='grid lg:grid-cols-2 gap-4 mb-12'>
                <div className='flex flex-1 my-12'>
                  <div className='flex justify-center items-center text-lg font-weight-bold rounded-md text-white px-1 h-fit mr-2 mt-1'>
                    <Image
                      src="/imgs/number_1.png"
                      alt="Number 1"
                      width={240}
                      height={240}
                      className={'h-fit'}
                    />
                  </div>
                  <div className='ml-4'>
                    <h1 className='text-md lg:text-2xl font-weight-bold leading-normal'>Our process is simple and straightforward.</h1>
                    <p className='text-sm lg:text-xl font-weight-400 leading-normal my-4'>
                      All you have to do is complete a private online assessment, where you’ll share information about your health history and any other prescriptions you’re taking.
                    </p>
                  </div>
                </div>
                <div className='flex flex-1 my-12'>
                  <div className='flex justify-center items-center text-lg font-weight-bold rounded-md text-white px-1 h-fit mr-2 mt-1'>
                    <Image
                      src="/imgs/number_2.png"
                      alt="Number 2"
                      width={240}
                      height={240}
                      className={'h-fit'}
                    />
                  </div>
                  <div className='ml-4'>
                    <h1 className='text-md lg:text-2xl font-weight-bold leading-normal'>Expect a message from a doctor or nurse practitioner within 24 hours.</h1>
                    <p className='text-sm lg:text-xl font-weight-400 leading-normal my-4'>
                      Within 1 day, one of our licensed doctors or nurse practitioners will message you to discuss your symptoms and prescribe medication if appropriate.
                    </p>
                  </div>
                </div>
                <div className='flex flex-1 my-12'>
                  <div className='flex justify-center items-center text-lg font-weight-bold rounded-md text-white px-1 h-fit mr-2 mt-1'>
                    <Image
                      src="/imgs/number_3.png"
                      alt="Number 3"
                      width={320}
                      height={320}
                      className={'h-fit'}
                    />
                  </div>
                  <div className='ml-4'>
                    <h1 className='text-md lg:text-2xl font-weight-bold leading-normal'>Get speedy and cost-free delivery right to your doorstep.</h1>
                    <p className='text-sm lg:text-xl font-weight-400 leading-normal my-4'>
                      And the best part? Our prescriptions are delivered straight to your door in a discreet package, with FREE shipping in just 2-3 business days. Plus, if you’re already an ED patient, you can renew your prescription with a FREE visit.
                    </p>
                  </div>
                </div>
                <div className='flex flex-1 my-12'>
                  <div className='flex justify-center items-center text-lg font-weight-bold rounded-md text-white px-1 h-fit mr-2 mt-1'>
                    <Image
                      src="/imgs/number_4.png"
                      alt="Number 4"
                      width={320}
                      height={320}
                      className={'h-fit'}
                    />
                  </div>
                  <div className='ml-4'>
                    <h1 className='text-md lg:text-2xl font-weight-bold leading-normal'>At UpLink Health Health, we’re committed to providing our patients with the highest level of care and convenience.</h1>
                    <p className='text-sm lg:text-xl font-weight-400 leading-normal my-4'>
                      That’s why we offer monthly delivery for 11 refills, with the option to request up to 3 refills at a time. And if you ever have any questions or concerns, our team is here to help - just give us a call or send us a message
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className='flex flex-1 justify-center my-4 lg:my-4'>
              <Image
                src='/imgs/delivery-bg-3.png'
                alt='certification'
                width={600}
                height={400}
                className={'rounded-2xl h-fit'}
                priority
              />
            </div>
            <div className='flex flex-1 flex-col items-center justify-center lg:ml-3 px-2 lg:px-6'>
              <div className='flex flex-col items-center'>
                <h1 className='text-xl lg:text-3xl font-weight-bold leading-tight text-center'>Don’t let ED hold you back any longer.</h1>
                <Divider className='my-4 lg:my-8' />
                <p className='text-sm lg:text-lg font-weight-bold mt-2 mb-2 text-gray-600'>Try UpLink Health Health today and experience the convenience and privacy of telehealth. We’re a national company based in San Francisco, CA, and we’re here to help you get the treatment you need, when you need it.</p>
              </div>
            </div>
          </div>
        </div>
        <div className={`w-full ${styles.bgWhite}`}>
          <div className='flex justify-between px-4 py-4 lg:px-24 lg:py-24 container mx-auto flex-col lg:flex-row'>
            <div className={`flex flex-1 rounded-2xl p-4 lg:p-12 lg:mr-5 ${styles.infoCard} flex-col lg:flex-row`}>
              <div className='bg-[#85aec2] p-4 flex justify-center items-center w-fit h-fit rounded-xl mt-8'>
                <Image
                  src="/imgs/blood-pressure-icon.png"
                  alt="blood-pressure-icon"
                  width={550}
                  height={550}
                  className={'lg:mt-2 w-8 lg:w-auto'}
                />
              </div>
              <div className='lg:p-5 lg:ml-6 mt-2 lg:mt-0'>
                <p className='text-md lg:text-2xl font-weight-bold mb-2'>To prescribe ED medication, our medical team requires your blood pressure reading. If you don't already know your levels, locate the nearest blood pressure machine.</p>
              </div>
            </div>
            <div className={`flex flex-1 rounded-2xl p-4 lg:p-12 lg:ml-5 ${styles.infoCard} flex-col lg:flex-row mt-4 lg:mt-0`}>
              <div className='bg-[#85aec2] p-4 flex justify-center items-center w-fit h-fit rounded-xl mt-8'>
                <Image
                  src="/imgs/power-icon.png"
                  alt="power-icon"
                  width={350}
                  height={350}
                  className={'lg:mt-2 w-8 lg:w-auto'}
                />
              </div>
              <div className='lg:p-5 lg:ml-6 mt-2 lg:mt-0'>
                <p className='text-md lg:text-2xl font-weight-bold mb-4'>By the time they reach 40 years old, as many as 40% of men experience erectile dysfunction (ED).</p>
                <Button title="Learn More" containerClassName='mt-6' type={ButtonType.redOutline} />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
